name: intl_generator
version: 0.4.1
description: >-
  Contains code to deal with internationalized/localized messages,
  date and number formatting and parsing, bi-directional text, and
  other internationalization issues.

homepage: https://github.com/kiwi-bop/intl_generator
environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  collection: ">=1.15.0 "
  analyzer: ">=2.1.0 "
  args: ">=2.1.0"
  dart_style: ^3.1.2
  intl: ">=0.17.0 "
  path: ">=1.8.0 "
  petitparser: ^7.0.1
dev_dependencies:
  test: ^1.26.3
